version: '3.7'

volumes:
  fastapi-data:
  pg-data:

networks:
  backend:
  traefik-public:
    external: true

services:

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=oeh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    networks: [ backend ]
    volumes:
      - pg-data:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi
    image: community.docker.edu-sharing.com/metaqs-api-fastapi:latest
    depends_on: [ postgres ]
    environment:
      - API_KEY=${API_KEY}
      - PROJECT_NAME="MetaQS API"
      - API_VERSION=v1
      - LOG_LEVEL=error
      - ALLOWED_HOSTS=*
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=oeh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    networks:
      - backend
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:metalookup.openeduhub.net
        - traefik.enable=true
        - traefik.port="${PORT}"
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
    volumes:
      - fastapi-data:/var/lib/fastapi/data
#    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --log-level error
